automation, refactoring, optimizing, etc.
xtrime-ru/antizapret-vpn-docker pull request #22
Opened 2024-08-12 01:55 UTC by flameshikari

2024-08-12 12:21 UTC, xtrime-ru requested changes

2024-08-12 12:21 UTC, xtrime-ru commented on rootfs/init.sh
> +        if test $(find /root/antizapret/result/$FILE -mmin +360); then
Я бы лучше эту логику добавил в doall.sh через patch. 

Тогда doall можно было бы запускать сразу при старте (не нужно правило systemd править).  Doall бы пропускал загрузку правио, но всеравно делал парсинг (так как правила пользовательские могут отличаться от того что было при предыдущей сборке конфигов)

Если хотим и парсинг пропускать, то надо хранить md5 хеши всех правил, что бы иметь гарантию что ничего не поменялось. Тогда можно после загрузки списков пропускать parse.sh, если ниче не поменялось.

2024-08-12 12:21 UTC, xtrime-ru commented on rootfs/root/dnsmap/proxy.py
> +UPSTREAM_DNS = os.getenv('UPSTREAM_DNS', '1.1.1.1:53')
Где используется переменная?  И ты не прокинул ее в конфиге systemd

2024-08-12 12:21 UTC, xtrime-ru commented on rootfs/init.sh
> +    waiter="until ps -p 1 | grep -q systemd; do sleep 1; done; sleep 1"
Красиво! Но раз это цикл, то можно сократить sleep и сделать 0.1

2024-08-12 12:21 UTC, xtrime-ru commented on rootfs/init.sh
> +postrun journalctl -f
Нужно передавать --since, иначе часть логов пропадет.

2024-08-12 12:21 UTC, xtrime-ru commented on rootfs/etc/knot-resolver/kresd.conf
> +    local ip = resolve(dns)
Давай эту логику вынесем в init.sh. И просто будем менять env DNS на его ip. 

Типа 
1) Проверяем ругуляркой, что  "$DNS" является ip адресом. 
2) Если он не ip, то резовлим его через nslookup или dig и записываем результат в DNS. 
3) если не получилось резолвнуть - то exit 1

2024-08-12 12:36 UTC, flameshikari commented on rootfs/init.sh
> +echo 127.0.1.1 $HOSTNAME >> /etc/hosts
Это сделано на основе шаблонов в [LXD-контейнере](https://bitbucket.org/anticensority/antizapret-vpn-container/src/master/mkosi/extra/lxd/templates/). Зачем это нужно не совсем понятно, но на всякий случай сделано.

2024-08-12 12:39 UTC, flameshikari commented on docker-compose.yml
> +      - /etc/timezone:/etc/timezone:ro
Делает, но там часовой пояс UTC. Это для удобства. И как выяснилось, `/etc/timezone` необязателен, достаточно `/etc/localtime`.

2024-08-12 12:41 UTC, flameshikari commented on rootfs/etc/knot-resolver/kresd.conf
> +    local ip = resolve(dns)
Отличная идея. Изначально у меня было что-то похожее сделано, но без логики на проверку адреса.

2024-08-12 12:43 UTC, flameshikari commented on rootfs/root/dnsmap/proxy.py
> +UPSTREAM_DNS = os.getenv('UPSTREAM_DNS', '1.1.1.1:53')
Я случайно не те изменения применил при разрешении конфликта; верну обратно исходный файл.

2024-08-12 12:46 UTC, flameshikari commented on config/adguard/AdGuardHome.yaml
> +    password: $2a$10$NvCUwIsoFwURzBP20AcdKOnOK/h/fVSCuvhdCNNimv0O8e0Mb3jgK
Наверное, да, не самая хорошая идея была оставлять конфиг. Но идея была такая, что пользователь запустит контейнер AdGuardHome и всё из коробки работает без настроек. В любом случае, пользователь может поменять пароль через админку.

2024-08-12 12:47 UTC, flameshikari commented on rootfs/root/openvpn/generate.sh
> +export PORT=${PORT:-1194}
Не, скрипт запускается только через `init.sh` и нормально подхватывает переменные.

2024-08-12 12:59 UTC, flameshikari commented on rootfs/etc/openvpn/server/keys/dh2048.pem
Идея такая, что пользователь может изменить путь хоста в маунте `./keys:/etc/openvpn` на желаемый, и если папка пуста, то она автоматически пополнится необходимыми файлами, которые после не перезаписываются, если они присутствуют в папке. Не знаю, есть ли такая практика, но по ощущениям подобное поведение почти у всех контейнеров наблюдается.

Вообще, я это пробовал и со списками делать, чтобы вместо точечного монтирования всех списков хватало монтирования одной папки, которая точно так же пополнится нужными файлами без последующей перезаписи.

Например, если пользователь не хочет клонировать репозиторий и хочет просто спуллить контейнер из Docker Hub с удобными ему параметрами запуска, то это отличное решение.

2024-08-12 12:59 UTC, flameshikari commented on rootfs/init.sh
> +cp -rv --update=none /rootfs/etc/openvpn/* /etc/openvpn
https://github.com/xtrime-ru/antizapret-vpn-docker/pull/22#discussion_r1713723431

2024-08-12 13:03 UTC, flameshikari commented on rootfs/init.sh
> +        if test $(find /root/antizapret/result/$FILE -mmin +360); then
Согласен, всё же лучше будет логику скрипта расширить.

2024-08-13 17:04 UTC, xtrime-ru commented on rootfs/etc/knot-resolver/kresd.conf
> +policy.add(
Так нельзя оставлять. Например adguard не будет работать для RU доменов. Либо удалять возможно сосвсем удалить это, либо вернуть if/else и не сетить по умолчанию DNS.

2024-08-13 17:07 UTC, xtrime-ru commented on rootfs/init.sh
> +iptables-legacy-save > /etc/iptables.rules
Давай закоментим или уберем этот костыль? Я пока не понимаю как он в нормальной ситуации может повлиять на систему.

2024-08-13 17:11 UTC, xtrime-ru commented on docker-compose.adguard.yml
> +      - /etc/localtime:/etc/localtime:ro
не надо

2024-08-13 17:14 UTC, xtrime-ru commented on rootfs/init.sh
> +DNS_RU=$(resolve $DNS_RU 77.88.8.8)
А DOMAIN и PORT ?

2024-08-13 17:18 UTC, flameshikari commented on docker-compose.adguard.yml
> +      - /etc/localtime:/etc/localtime:ro
Ладно, пользователи сами будут добавлять.

2024-08-13 17:50 UTC, flameshikari commented on rootfs/init.sh
> +DNS_RU=$(resolve $DNS_RU 77.88.8.8)
Нет особого смысла туда их добавлять, ибо они нужны только на стадии инициализации контейнера (перед запуском инит-системы).

2024-08-13 18:14 UTC, xtrime-ru commented on rootfs/init.sh
>  postrun journalctl -f --no-hostname --since '2000-01-01 00:00:00'
Тут логи будут дублироваться при перезапуске :) 
Я же делал переменную start = $(date +%T)

2024-08-13 18:15 UTC, flameshikari commented on rootfs/init.sh
>  postrun journalctl -f --no-hostname --since '2000-01-01 00:00:00'
А, понял! Сейчас поправлю.

2024-08-18 15:08 UTC, merged